examen_parcial/examen_parcial/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestion_tienda.urls'))
]

examen_parcial/gestion_tienda/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'gestion_tienda'
urlpatterns = [
    path('',views.index,name='index'),
    path('gestionUsuarios',views.gestionUsuarios,name='gestionUsuarios'),
    path('gestionProductos',views.gestionProductos,name='gestionProductos'),
    path('cerrarSesion',views.cerrarSesion,name='cerrarSesion'),
    path('eliminarUsuario/<str:ind>',views.eliminarUsuario,name='eliminarUsuario'),
    path('eliminarProducto/<str:ind>',views.eliminarProducto,name='eliminarProducto'),
    path('verUsuario/<str:ind>',views.verUsuario,name='verUsuario'),
    path('nuevoProducto',views.nuevoProducto,name='nuevoProducto'),

]

examen_parcial/gestion_tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Create your models here.
class datosUsuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Nombre = models.CharField(default='NOMBRE',max_length=30)
    Apellido =models.CharField(default='APELLIDO',max_length=30)
    Email = models.EmailField()
    Username = models.CharField(default='USERNAME',max_length=30)
    Contrasena = models.CharField(default='PASSWORD',max_length=30)
    RolUsuario = models.CharField(default='ROL',max_length=512)
    NoCelular = models.CharField(default='999999999',max_length=11)
    FechaIngreso = models.DateField(default=date.today)

class Producto(models.Model):
    NombreProducto=models.CharField(default='NOMBREPRODUCTO',max_length=30)
    Codigo=models.CharField(default='CODIGO',max_length=30)
    PrecioCompra=models.FloatField(default=0.00)
    PrecioVenta=models.FloatField(default=0.00)
    Usuario=models.ForeignKey(User,on_delete=models.CASCADE)

class tareasInformacion(models.Model):
    usuarioRelacionado=models.ForeignKey(User,on_delete=models.CASCADE)
    descripcionTarea=models.CharField(default='',max_length=512)
    fechaInicio=models.DateField(default=date.today)
    fechaFin=models.DateField(default=date.today)
    estadoTarea=models.CharField(default='PROCESO',max_length=30)

examen_parcial/gestion_tienda/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import datosUsuario,tareasInformacion,Producto
from datetime import date
import datetime
def index(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')   
        usuarioInfo = authenticate(request,username=nombreUsuario,password=contraUsuario)
        if usuarioInfo is not None:
            login(request,usuarioInfo)
            if usuarioInfo.datosusuario.RolUsuario=='ADMINISTRADOR':
                return HttpResponseRedirect(reverse('gestion_tienda:gestionUsuarios'))
            else:
                return HttpResponseRedirect(reverse('gestion_tienda:gestionProductos'))
        else:
            return HttpResponseRedirect(reverse('gestion_tienda:index'))
    return render(request,'ingresoUsuario.html')
@login_required(login_url='http://127.0.0.1:8000')
def cerrarSesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('gestion_tienda:index'))

@login_required(login_url='http://127.0.0.1:8000')
def gestionUsuarios(request):
    if request.user.datosusuario.RolUsuario=='ADMINISTRADOR':
        if request.method=='POST':
            usernameUsuario=request.POST.get('usernameUsuario')
            nombreUsuario=request.POST.get('nombreUsuario')
            apellidoUsuario=request.POST.get('apellidoUsuario')
            emailUsuario=request.POST.get('emailUsuario')
            contraUsuario=request.POST.get('contraUsuario')
            rolUsuario=request.POST.get('rolUsuario')
            celularUsuario=request.POST.get('celularUsuario')
            usuarioNuevo=User.objects.create(
                username=usernameUsuario,
                email=emailUsuario
            )
            usuarioNuevo.set_password(contraUsuario)
            usuarioNuevo.first_name=nombreUsuario
            usuarioNuevo.last_name=apellidoUsuario
            usuarioNuevo.is_staff=True
            usuarioNuevo.save()
            datosUsuario.objects.create(
                user=usuarioNuevo,
                Nombre=nombreUsuario,
                Apellido=apellidoUsuario,
                Email=emailUsuario,
                Username=usernameUsuario,
                Contrasena=contraUsuario,
                RolUsuario=rolUsuario,
                NoCelular=celularUsuario
            )
            return HttpResponseRedirect(reverse('gestion_tienda:gestionUsuarios'))
        return render(request,'gestionUsuarios.html',{
        'usuariosTotales':User.objects.all().order_by('id')           
        })
    else:
        return HttpResponseRedirect(reverse('gestion_tienda:gestionProductos'))
def gestionProductos(request):
    #usuarioInfo=request.user
    productosUsuario=Producto.objects.all()
    return render(request,'gestionProductos.html',{
        'productosUsuario': productosUsuario
    })
def eliminarUsuario(request,ind):
    usuarioEliminar = User.objects.get(id=ind)
    datosUsuario.objects.get(user=usuarioEliminar).delete()
    usuarioEliminar.delete()
    return HttpResponseRedirect(reverse('gestion_tienda:gestionUsuarios'))
def eliminarProducto(request,ind):
    productoEliminar = Producto.objects.get(id=ind)
    productoEliminar.delete()
    print('Producto eliminado')
    return HttpResponseRedirect(reverse('gestion_tienda:gestionProductos'))
def verUsuario(request, ind):
    if (request.user.datosusuario.RolUsuario=='ADMINISTRADOR'):
        usuarioInfo=User.objects.get(id=ind)
        #productosUsuario=Producto.objects.all()
        return render(request,'informacionUsuario.html',{
            'usuarioInfo' : usuarioInfo,
            #'productosUsuario': productosUsuario,
        })
    else:
        return HttpResponseRedirect(reverse('gestion_tienda:gestionProductos'))
def nuevoProducto(request):
    if request.method=='POST':
        usuarioRelacionado=request.user
        nombreProducto=request.POST.get('NombreProducto')
        codigo=request.POST.get('Codigo')
        precioCompra=request.POST.get('PrecioCompra')
        precioVenta=request.POST.get('PrecioVenta')
        Producto.objects.create(
            NombreProducto=nombreProducto,
            Codigo=codigo,
            Usuario=usuarioRelacionado,
            PrecioCompra=precioCompra,
            PrecioVenta=precioVenta,
        )
        return HttpResponseRedirect(reverse('gestion_tienda:gestionProductos'))

examen_parcial/gestion_tienda/templates/gestionProductos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Gestion de productos</title>
</head>
<body>
    <div class="bg-dark">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-4 mt-3 mb-3 text-white">
                    <div class="row">
                        <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                    </div>
                    <div class="row">
                        <h5>{{ user.datosusuario.RolUsuario}}</h5>
                    </div>
                </div>
                {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionUsuarios' %}">Gestion de usuarios</a>
                </div>
                {% endif %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionProductos' %}">Gestion de productos</a>
                </div>
                <div class="col-1">
                    <a class="btn btn-success" href="{% url 'gestion_tienda:cerrarSesion' %}">
                       <i class="fa-solid fa-right-to-bracket"></i>Salir
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5 text-center mb-3">
        <h1>Gestion de productos</h1>
    </div>
    <div class="container mt-5">
        <div class="row justify-content-between">
            <div class="col-2 text-start">
                <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto"><i class="fa-solid fa-calendar-plus"></i>Nuevo Producto</button>
            </div>
        </div>
    </div>
    <div class="mt-5 container">
        <div class="row justify-content-center">
            <div class="col-8">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <th>Nombre de producto</th>
                        <th>Codigo de producto</th>
                        <th>Precio de compra</th>
                        <th>Precio de venta</th>
                        <th>Usuario que lo agrego</th>
                        {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
                        <th>Eliminar producto</th>
                        {% endif %}
                    </thead>
                    <tbody>
                        {% for producto in productosUsuario %}
                        <tr>
                            <td>{{ producto.NombreProducto }}</td>
                            <td>{{ producto.Codigo }}</td>
                            <td>{{ producto.PrecioCompra}}</td>
                            <td>{{ producto.PrecioVenta}}</td>
                            <td>{{ producto.Usuario.datosusuario.Nombre}}</td>
                            {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
                            <td><a href="{% url 'gestion_tienda:eliminarProducto' producto.id%}" class="btn btn-danger">
                                <i class="fa-solid fa-trash"></i>
                            </a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>
<!--Nuevo producto-->
<!--Ventana modal-->
<div class="modal fade" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false" >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'gestion_tienda:nuevoProducto' %}">
            {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear nuevo producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Nombre de producto</label>
                            <input class="form-control" type="text" required name="NombreProducto">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Codigo de producto</label>
                            <input class="form-control" type="text" required name="Codigo">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <lable>Precio de compra</lable>
                            <input class="form-control" type="float" required name="PrecioCompra">
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <lable>Precio de venta</lable>
                            <input class="form-control" type="float" required name="PrecioVenta">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

examen_parcial/gestion_tienda/templates/gestionUsuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Gestion de usuarios</title>
</head>
<body>
    <div class="bg-dark">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-4 mt-3 mb-3 text-white">
                    <div class="row">
                        <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                    </div>
                    <div class="row">
                        <h5>{{ user.datosusuario.RolUsuario}}</h5>
                    </div>
                </div>
                {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionUsuarios' %}">Gestion de usuarios</a>
                </div>
                {% endif %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionProductos' %}">Gestion de productos</a>
                </div>
                <div class="col-1">
                    <a class="btn btn-success" href="{% url 'gestion_tienda:cerrarSesion' %}">
                       <i class="fa-solid fa-right-to-bracket"></i>Salir
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5 text-center">
        <h1>Gestion de usuarios</h1>
    </div>
    <div class="mt-5 container">
        <div class="row justify-content-between">
            <div class="col-2">
                <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoUsuario">
                    <i class="fa-solid fa-user-plus"></i>
                    Crear usuario
                </button>
            </div>

        </div>
    </div>
    <div class="mt-5 container">
        <div class="row justify-content-center">
            <div class="col-8">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Numero de celular</th>
                        <th>Fecha de registro</th>
                        <th>Ver</th>
                        <th>Editar</th>
                        <th>Eliminar</th>
                    </thead>
                    <tbody>
                        {%for usuario in usuariosTotales%}
                        <tr>
                            <td>{{ usuario.first_name }}</td>
                            <td>{{ usuario.last_name }}</td>
                            <td>{{ usuario.datosusuario.NoCelular }}</td>
                            <td>{{ usuario.datosusuario.FechaIngreso }}</td>
                            <td class="text-center"><a class="btn btn-info" href="{% url 'gestion_tienda:verUsuario' usuario.id %}">
                                <i class="fa-solid fa-eye"></i>
                                </a> 
                            </td>
                            <td class="text-center"><a class="btn btn-warning" href="#">
                                <i class="fa-solid fa-edit"></i>
                                </a> 
                            </td>
                            <td class="text-center"><a class="btn btn-danger" href="{%url 'gestion_tienda:eliminarUsuario' usuario.id %}">
                                <i class="fa-solid fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>
<!--Nuevo usuario-->
<!--Ventana modal-->
<div class="modal fade" id="nuevoUsuario" data-bs-backdrop="static" data-bs-keyboard="false" >
<div class="modal-dialog modal-dialog-centered">

    <div class="modal-content">
    <form method="post" action="{% url 'gestion_tienda:gestionUsuarios' %}">
    {% csrf_token %}
        <div class="modal-header">
        <h5 class="modal-title">Crear nuevo usuario</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="row form-group justify-content-around mb-3">
                <div class="col-5">
                    <label>Username:</label>
                    <input class="form-control" type="text" name="usernameUsuario" required>
                </div>
                <div class="col-5">
                    <label>Contrasena:</label>
                    <input class="form-control" type="password" name="contraUsuario" required>
                </div>
            </div>
            <div class="row form-group justify-content-around mb-3">
                <div class="col-5">
                    <label>Nombre :</label>
                    <input class="form-control" type="text" name="nombreUsuario" required>
                </div>
                <div class="col-5">
                    <label>Apellido:</label>
                    <input class="form-control" type="text" name="apellidoUsuario" required>
                </div>
            </div>
            <div class="row form-group justify-content-around mb-3">
                <div class="col-5">
                    <label>Email :</label>
                    <input class="form-control" type="email" name="emailUsuario" required>
                </div>
                <div class="col-5">
                    <label>RolUsuario:</label>
                    <select class="form-select" name="rolUsuario">
                        <option value="VENDEDOR">Vendedor</option>
                        <option value="ADMINISTRADOR">Administrador</option>
                    </select>
                </div>
            </div>
            <div class="row form-group justify-content-around mb-3">
                <div class="col-5">
                    <label>Numero de celular:</label>
                    <input class="form-control" type="text" name="celularUsuario" required>
                </div>
            </div>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Registrar</button>
        </div>
    </form>
    </div>
</div>
</div>

examen_parcial/gestion_tienda/templates/informacionUsuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Gestion de usuarios</title>
</head>
<body>
    <div class="bg-dark">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-4 mt-3 mb-3 text-white">
                    <div class="row">
                        <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                    </div>
                    <div class="row">
                        <h5>{{ user.datosusuario.RolUsuario}}</h5>
                    </div>
                </div>
                {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionUsuarios' %}">Gestion de usuarios</a>
                </div>
                {% endif %}
                <div class="col">
                    <a class="btn btn-info" href="{% url 'gestion_tienda:gestionProductos' %}">Gestion de productos</a>
                </div>
                <div class="col-1">
                    <a class="btn btn-success" href="{% url 'gestion_tienda:cerrarSesion' %}">
                       <i class="fa-solid fa-right-to-bracket"></i>Salir
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5 text-center">
        <h1>Gestion de usuarios</h1>
    </div>
    {% if user.datosusuario.RolUsuario == 'ADMINISTRADOR' %}
    <div class="container mt-3 mb-3">
        <div>
            <a href="{% url 'gestion_tienda:gestionUsuarios' %}" class="btn btn-info"><i class="fa-solid fa-arrow-left"></i>
            </a>
        </div>
    </div>
    {% endif %}
    <div class="mt-5 text-center mb-3">
        <h3>Informacion del usuario: {{ usuarioInfo.first_name }} {{ usuarioInfo.last_name }}</h3>
    </div>
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-5 bg-light" style="border-radius: 20px;">
                <div class="row mb-2 mt-2">
                    <div class="col-5">
                        <h5>Nombre completo : </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.first_name }} {{ usuarioInfo.last_name }}</i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-5">
                        <h5>Nombre de usuario : </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.username }}</i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-5">
                        <h5>Email: </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.datosusuario.Email }} </i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-5">
                        <h5>Numero de celular: </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.datosusuario.NoCelular }} </i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-5">
                        <h5>Rol de usuario: </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.datosusuario.RolUsuario }} </i>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-5">
                        <h5>Fecha de ingreso: </h5>
                    </div>
                    <div class="col-7">
                        <i>{{ usuarioInfo.datosusuario.FechaIngreso|date:"d-m-y" }} </i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

examen_parcial/gestion_tienda/templates/ingresoUsuario.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Vista de Ingreso</title>
</head>
<body class="bg-dark">
    <div class="bg-white position-absolute start-50 top-50 translate-middle" style="height: 350px; width: 400px;border-radius: 20px;">
        <div class="position-absolute start-50 top-50 translate-middle bg-white text-center" style="width: 300px;height: 300px">
            <form method="post" action="{% url 'gestion_tienda:index' %}">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <h1>Log in</h1>
                </div>
                <div class="form-group mb-3">
                    <label>Ingrese su nombre de usuario</label>
                    <input class="form-control" type="text" name="nombreUsuario" placeholder="Username">
                </div>
                <div class="form-group mb-3">
                    <label>Ingrese su contrasena</label>
                    <input class="form-control" type="password" name="contraUsuario" placeholder="Password">
                
                </div>
                <button type="submit" class="btn btn-info mb-3">
                    <i class="fa-solid fa-right-to-bracket"></i>
                    Log in
                </button>
            </form>
        </div>
    </div>
</body>
</html>